name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install 
          npm install 

      - name: Copy files to EC2
        uses: appleboy/scp-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /var/www/Hotel_Miranda_LARAVEL

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Hotel_Miranda_LARAVEL
            php artisan migrate
            php artisan config:cache
            php artisan route:cache
            systemctl restart apache2 

