name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 35.180.58.242
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/Hotel_Miranda_LARAVEL
            git pull 
            php artisan migrate
            php artisan config:cache
            php artisan route:cache
            systemctl restart apache2 
